# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "cargt"
BBFILE_PATTERN_cargt := "^${LAYERDIR}/"
BBFILE_PRIORITY_cargt = "10"

EULA_FILE_ST:stm32mpcommonmx = "${LAYERDIR}/conf/eula/${MACHINE}"
EULA_FILE_ST_MD5SUM:stm32mpcommonmx = "8b505090fb679839cefbcc784afe8ce9"

# Set a variable to get the STM32MP BSP location
CARGT_BASE = "${LAYERDIR}"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_cargt = "1"
LAYERSERIES_COMPAT_cargt = "scarthgap"

LAYERDEPENDS_cargt = " "
# dependency with meta-networking for netperf, ntp
LAYERDEPENDS_cargt += " networking-layer "
# dependency with meta-webserver for netdata
LAYERDEPENDS_cargt += " webserver "
# dependency with meta-gnome for stsprof
LAYERDEPENDS_cargt += " gnome-layer "
# dependency with meta-multimedia for gstreamer dependency (faac)
LAYERDEPENDS_cargt += " multimedia-layer"

INHERIT += "check-st-openstlinux-compatibility"
# OpenSTLinux compatibility version
ST_OSTL_COMPATIBILITY_VERSION_cargt = "6.2"
